
Transform: AWS::Serverless-2016-10-31

Resources:
  ResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python2.7
      CodeUri: boto3
      Handler: resource.handler
      Policies: PowerUserAccess

  MacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      CodeUri: boto3
      Handler: macro.handler
      Policies: PowerUserAccess
      Environment:
        Variables:
          LAMBDA_ARN: !GetAtt ResourceFunction.Arn

  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: boto3
      FunctionName: !GetAtt MacroFunction.Arn
